"""initial scraper schema

Revision ID: 001_initial_schema
Revises: None
Create Date: 2026-03-19 00:00:00
"""

from __future__ import annotations

from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa

revision = "001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def _month_start(value: datetime) -> datetime:
    return value.astimezone(timezone.utc).replace(day=1, hour=0, minute=0, second=0, microsecond=0)


def _add_months(value: datetime, months: int) -> datetime:
    month_index = value.month - 1 + months
    year = value.year + month_index // 12
    month = month_index % 12 + 1
    return value.replace(year=year, month=month, day=1)


def _create_partition(start: datetime) -> None:
    end = _add_months(start, 1)
    table_name = f"player_samples_{start:%Y_%m}"
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {table_name}
        PARTITION OF player_samples
        FOR VALUES FROM ('{start.isoformat()}') TO ('{end.isoformat()}');
        """
    )


def upgrade() -> None:
    tier_enum = sa.Enum("hot", "warm", "cold", name="tier_enum", native_enum=False)

    op.create_table(
        "tracked_apps",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("source_game_public_id", sa.String(length=64), nullable=True),
        sa.Column("source_game_id", sa.Integer(), nullable=True),
        sa.Column("steam_app_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("import_source", sa.String(length=64), nullable=False, server_default=sa.text("'backend_api'")),
        sa.Column("manual_tier_override", tier_enum, nullable=True),
        sa.Column("effective_tier", tier_enum, nullable=False, server_default=sa.text("'warm'")),
        sa.Column("last_imported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_known_players", sa.Integer(), nullable=True),
        sa.Column("latest_24h_high", sa.Integer(), nullable=True),
        sa.Column("latest_24h_low", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("steam_app_id", name="uq_tracked_apps_steam_app_id"),
    )
    op.create_index("idx_tracked_apps_source_public_id", "tracked_apps", ["source_game_public_id"])
    op.create_index("idx_tracked_apps_source_game_id", "tracked_apps", ["source_game_id"])
    op.create_index("idx_tracked_apps_steam_app_id", "tracked_apps", ["steam_app_id"])
    op.create_index("idx_tracked_apps_last_polled_at", "tracked_apps", ["last_polled_at"])

    op.execute(
        """
        CREATE TABLE player_samples (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            tracked_app_id INTEGER NOT NULL REFERENCES tracked_apps(id) ON DELETE CASCADE,
            steam_app_id INTEGER NOT NULL,
            sampled_at TIMESTAMPTZ NOT NULL,
            concurrent_players INTEGER NOT NULL,
            provider VARCHAR(64) NOT NULL DEFAULT 'steam_current_players',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (id, sampled_at),
            CONSTRAINT uq_player_samples_app_time UNIQUE (steam_app_id, sampled_at)
        ) PARTITION BY RANGE (sampled_at);
        """
    )
    op.execute("CREATE INDEX idx_player_samples_lookup ON player_samples (steam_app_id, sampled_at);")
    op.execute("CREATE INDEX idx_player_samples_tracked_app_id ON player_samples (tracked_app_id);")

    current_month = _month_start(datetime.now(timezone.utc))
    _create_partition(_add_months(current_month, -1))
    _create_partition(current_month)
    _create_partition(_add_months(current_month, 1))

    op.create_table(
        "player_activity_hourly",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("tracked_app_id", sa.Integer(), sa.ForeignKey("tracked_apps.id", ondelete="CASCADE"), nullable=False),
        sa.Column("steam_app_id", sa.Integer(), nullable=False),
        sa.Column("bucket_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_ending_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_24h_high", sa.Integer(), nullable=False),
        sa.Column("observed_24h_low", sa.Integer(), nullable=False),
        sa.Column("latest_players", sa.Integer(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("effective_tier_at_capture", tier_enum, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("steam_app_id", "bucket_started_at", name="uq_player_activity_hourly_app_bucket"),
    )
    op.create_index("idx_player_activity_hourly_tracked_app_id", "player_activity_hourly", ["tracked_app_id"])
    op.create_index("idx_player_activity_hourly_lookup", "player_activity_hourly", ["steam_app_id", "bucket_started_at"])

    op.create_table(
        "job_runs",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("job_name", sa.String(length=128), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("success_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("failure_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("error_summary", sa.Text(), nullable=True),
    )
    op.create_index("idx_job_runs_name_started", "job_runs", ["job_name", "started_at"])


def downgrade() -> None:
    op.drop_index("idx_job_runs_name_started", table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_index("idx_player_activity_hourly_lookup", table_name="player_activity_hourly")
    op.drop_index("idx_player_activity_hourly_tracked_app_id", table_name="player_activity_hourly")
    op.drop_table("player_activity_hourly")
    op.execute("DROP TABLE IF EXISTS player_samples CASCADE;")
    op.drop_index("idx_tracked_apps_last_polled_at", table_name="tracked_apps")
    op.drop_index("idx_tracked_apps_steam_app_id", table_name="tracked_apps")
    op.drop_index("idx_tracked_apps_source_game_id", table_name="tracked_apps")
    op.drop_index("idx_tracked_apps_source_public_id", table_name="tracked_apps")
    op.drop_table("tracked_apps")
